tweets: markov_chain.h linked_list.h
	gcc -Wall -Wextra -Wvla -std=c99 linked_list.c tweets_generator.c markov_chain.c -o tweets_generator
#make tweets

snake: snakes_and_ladders.c markov_chain.c markov_chain.h
	gcc -Wall -Wextra -Wvla -std=c99 linked_list.c snakes_and_ladders.c markov_chain.c -o snakes_and_ladders
